// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/events" | "/admin/logs" | "/admin/tickets" | "/admin/users" | "/dashboard" | "/events/[slug]" | "/events/[slug]/pay/[ticketTypeId]" | "/events/[slug]/register/[ticketTypeId]" | "/help" | "/login" | "/organizer" | "/organizer/events" | "/organizer/events/[eventId]/attendees" | "/organizer/events/[eventId]/edit" | "/organizer/events/[eventId]/payments" | "/organizer/events/new" | "/payments" | "/profile" | "/register" | "/scanner" | "/settings" | "/tickets" | "/tickets/[publicId]"
type AppRouteHandlerRoutes = "/api/admin/events/[eventId]" | "/api/admin/tickets/[ticketId]" | "/api/admin/users" | "/api/admin/users/[userId]" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/checkin/validate" | "/api/events/[eventId]/manual-payments" | "/api/events/[eventId]/register" | "/api/me" | "/api/organizer/events" | "/api/organizer/events/[eventId]" | "/api/organizer/events/[eventId]/ticket-types" | "/api/organizer/manual-payments/[paymentId]" | "/api/organizer/ticket-types/[ticketTypeId]" | "/api/scanner/events" | "/api/uploads" | "/api/uploads/[uploadId]" | "/organizer/events/[eventId]/attendees/export"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/organizer"
type RedirectRoutes = "/organizer/events/[eventId]/manual-payments" | "/organizer/events/[eventId]/tickets" | "/organizer/events/create" | "/scanner/checkin" | "/scanner/gates" | "/scanner/login" | "/student/payments" | "/student/profile" | "/student/tickets" | "/student/tickets/[publicId]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/events": {}
  "/admin/logs": {}
  "/admin/tickets": {}
  "/admin/users": {}
  "/api/admin/events/[eventId]": { "eventId": string; }
  "/api/admin/tickets/[ticketId]": { "ticketId": string; }
  "/api/admin/users": {}
  "/api/admin/users/[userId]": { "userId": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/checkin/validate": {}
  "/api/events/[eventId]/manual-payments": { "eventId": string; }
  "/api/events/[eventId]/register": { "eventId": string; }
  "/api/me": {}
  "/api/organizer/events": {}
  "/api/organizer/events/[eventId]": { "eventId": string; }
  "/api/organizer/events/[eventId]/ticket-types": { "eventId": string; }
  "/api/organizer/manual-payments/[paymentId]": { "paymentId": string; }
  "/api/organizer/ticket-types/[ticketTypeId]": { "ticketTypeId": string; }
  "/api/scanner/events": {}
  "/api/uploads": {}
  "/api/uploads/[uploadId]": { "uploadId": string; }
  "/dashboard": {}
  "/events/[slug]": { "slug": string; }
  "/events/[slug]/pay/[ticketTypeId]": { "slug": string; "ticketTypeId": string; }
  "/events/[slug]/register/[ticketTypeId]": { "slug": string; "ticketTypeId": string; }
  "/help": {}
  "/login": {}
  "/organizer": {}
  "/organizer/events": {}
  "/organizer/events/[eventId]/attendees": { "eventId": string; }
  "/organizer/events/[eventId]/attendees/export": { "eventId": string; }
  "/organizer/events/[eventId]/edit": { "eventId": string; }
  "/organizer/events/[eventId]/manual-payments": { "eventId": string; }
  "/organizer/events/[eventId]/payments": { "eventId": string; }
  "/organizer/events/[eventId]/tickets": { "eventId": string; }
  "/organizer/events/create": {}
  "/organizer/events/new": {}
  "/payments": {}
  "/profile": {}
  "/register": {}
  "/scanner": {}
  "/scanner/checkin": {}
  "/scanner/gates": {}
  "/scanner/login": {}
  "/settings": {}
  "/student/payments": {}
  "/student/profile": {}
  "/student/tickets": {}
  "/student/tickets/[publicId]": { "publicId": string; }
  "/tickets": {}
  "/tickets/[publicId]": { "publicId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/organizer": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
