// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events">> = Specific
  const handler = {} as typeof import("../../src/app/admin/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/logs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/events/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/events/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/events/[slug]/pay/[ticketTypeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[slug]/pay/[ticketTypeId]">> = Specific
  const handler = {} as typeof import("../../src/app/events/[slug]/pay/[ticketTypeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/events/[slug]/register/[ticketTypeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[slug]/register/[ticketTypeId]">> = Specific
  const handler = {} as typeof import("../../src/app/events/[slug]/register/[ticketTypeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../src/app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organizer/events/[eventId]/attendees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[eventId]/attendees">> = Specific
  const handler = {} as typeof import("../../src/app/organizer/events/[eventId]/attendees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organizer/events/[eventId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[eventId]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/organizer/events/[eventId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organizer/events/[eventId]/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/[eventId]/payments">> = Specific
  const handler = {} as typeof import("../../src/app/organizer/events/[eventId]/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organizer/events/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events/new">> = Specific
  const handler = {} as typeof import("../../src/app/organizer/events/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organizer/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer/events">> = Specific
  const handler = {} as typeof import("../../src/app/organizer/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organizer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organizer">> = Specific
  const handler = {} as typeof import("../../src/app/organizer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../src/app/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/scanner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scanner">> = Specific
  const handler = {} as typeof import("../../src/app/scanner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tickets/[publicId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tickets/[publicId]">> = Specific
  const handler = {} as typeof import("../../src/app/tickets/[publicId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/events/[eventId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/events/[eventId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/events/[eventId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tickets/[ticketId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tickets/[ticketId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tickets/[ticketId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkin/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkin/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkin/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[eventId]/manual-payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[eventId]/manual-payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[eventId]/manual-payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[eventId]/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[eventId]/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[eventId]/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organizer/events/[eventId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizer/events/[eventId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/organizer/events/[eventId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organizer/events/[eventId]/ticket-types/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizer/events/[eventId]/ticket-types">> = Specific
  const handler = {} as typeof import("../../src/app/api/organizer/events/[eventId]/ticket-types/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organizer/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizer/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/organizer/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organizer/manual-payments/[paymentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizer/manual-payments/[paymentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/organizer/manual-payments/[paymentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/organizer/ticket-types/[ticketTypeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizer/ticket-types/[ticketTypeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/organizer/ticket-types/[ticketTypeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scanner/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scanner/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/scanner/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/[uploadId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/[uploadId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/[uploadId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organizer/events/[eventId]/attendees/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/organizer/events/[eventId]/attendees/export">> = Specific
  const handler = {} as typeof import("../../src/app/organizer/events/[eventId]/attendees/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/organizer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/organizer">> = Specific
  const handler = {} as typeof import("../../src/app/organizer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
